### PR TITLE
Depends on postgresql-api plugin

### PR DESCRIPTION
**Pull request by jonesbusy**
Depends on postgresql-api plugin instead

### Testing done

Automated tests only

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by jonesbusy** [comment]
We need to be careful with this due to https://github.com/jenkins-infra/helpdesk/issues/3757

Version is considered older.

We might need to depends on 42.3.3 instead

**Review by timja — COMMENTED** [review]
Any chance you can submit a PR doing following "Versioning with wrapped components" on:
https://www.jenkins.io/doc/developer/publishing/releasing-cd/

to the api plugin?

**Comment by jonesbusy** [comment]
> Any chance you can submit a PR doing following "Versioning with wrapped components" on: https://www.jenkins.io/doc/developer/publishing/releasing-cd/
> 
> to the api plugin?

Sure I can do that. I think it's the best to keep the prefix

**Comment by jonesbusy** [comment]
Here : https://github.com/jenkinsci/postgresql-api-plugin/pull/61

When released I will update this PR

**Pull request merged**
